source "${0:a:h}/plugins/jujutsu.zsh"

SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true

SPACESHIP_USER_SHOW=needed # Display username only when required...
SPACESHIP_USER_SUFFIX="%F{8}@%f"
SPACESHIP_USER_COLOR="8"

SPACESHIP_HOST_SHOW="always"
SPACESHIP_HOST_SHOW_FULL=true
SPACESHIP_HOST_COLOR="#f5a97f"
SPACESHIP_HOST_PREFIX=
SPACESHIP_HOST_SUFFIX=

SPACESHIP_DIR_PREFIX=" "
SPACESHIP_DIR_TRUNC_REPO=false # Do not truncate path in repos
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_COLOR="0"

SPACESHIP_CHAR_SYMBOL_SUCCESS="%K{0}%F{7} \ueefe %f%k%F{0}\ue0b0%f"
SPACESHIP_CHAR_SYMBOL_FAILURE="%K{#ed8796}%F{#f0c6c6} \ueefe %f%k%F{#ed8796}\ue0b0%f"
SPACESHIP_CHAR_COLOR_SUCCESS=green
SPACESHIP_CHAR_COLOR_FAILURE=red
SPACESHIP_CHAR_SUFFIX=" "

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D{%H:%M:%S}'
SPACESHIP_TIME_COLOR=
SPACESHIP_TIME_PREFIX=
SPACESHIP_TIME_SUFFIX=

SPACESHIP_ASYNC_SYMBOL="..."
SPACESHIP_ASYNC_COLOR="red"

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL=
SPACESHIP_EXIT_CODE_PREFIX="%K{#ed8796}%F{#f0c6c6} "
SPACESHIP_EXIT_CODE_SUFFIX="%f%k"

SPACESHIP_EXEC_TIME_ELAPSED=1
SPACESHIP_EXEC_TIME_PRECISION=3
SPACESHIP_EXIT_CODE_SUFFIX=

SPACESHIP_JUJUTSU_SYMBOL="%{%b%}"

SPACESHIP_PROMPT_ORDER=(
	user
	host
	dir
	line_sep
	exit_code
	sudo
	char
)

SPACESHIP_RPROMPT_ORDER=(
	async
	jujutsu
	time
	exec_time
)
