plugin:
  stern-pods:
    shortCut: Ctrl-L
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
    background: false
    command: stern
    args:
      - --tail
      - 50
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
