"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "log"
editor = "subl -n -w"

[user]
email = "desk@pixelbloom.com"
name = "Justin Morris"

[signing]
behavior = "own"
backend = "gpg"
key = "9690366C"

[git]
sign-on-push = true
auto-local-bookmark = true
