# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
#
# https://ohmyposh.dev/docs

version: 2
final_space: true
disable_notice: true
console_title_template: "{{ .Shell }} in {{ .PWD }}"

blocks:
  - type: prompt
    alignment: left
    newline: true

    segments:
      - type: session
        style: diamond
        foreground: "#ffffff"
        background: "#c386f1"
        # leading_diamond: 
        trailing_diamond: 
        template: " {{ if .SSHSession }}<d>{{ .UserName }}@{{ end }}</d>{{ .HostName }} "

      - type: executiontime
        style: powerline
        powerline_symbol: 
        foreground: "#ffffff"
        background: "#8800dd"
        template: " <#fefefe></> {{ .FormattedMs }} "
        properties:
          threshold: 200
          style: round
          always_enabled: false

      - type: path
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "#61AFEF"
        properties:
          style: full
          mapped_locations:
           ~/Workspace: ""

  - type: rprompt
    alignment: right

    segments:
      - type: git
        style: powerline
        foreground: "#193549"
        background: "#ffeb3b"
        template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
        properties:
          branch_icon: ""
          commit_icon: "@"
          fetch_status: true

      - type: kubectl
        style: powerline
        powerline_symbol: 
        foreground: "#000000"
        background: "#ebcc34"
        background_templates:
          - "{{ if contains 'prod' .Context }} #e91e63 {{ end }}"
        template: " {{.Context}} "


transient_prompt:
  foreground: "#222"
  background: transparent
  template: "{{ .Segments.Path.Location }} > "

